name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Setup environment
      run: |
        sudo sh -c "echo 'deb http://security.ubuntu.com/ubuntu xenial-security main' >> /etc/apt/sources.list"
        sudo apt-get update
        sudo apt-get install libssl1.0.0 libuv1-dev libkrb5-dev libc6-dbg
        sudo snap install valgrind --classic
        pip3 install https://github.com/scylladb/scylla-ccm/archive/master.zip
        sudo sh -c "echo 2097152 >> /proc/sys/fs/aio-max-nr"

    - name: Build
      run: cmake -DCASS_BUILD_INTEGRATION_TESTS=ON . && make

    - name: Run integration tests on Scylla 5.0.0
      env:
#        Ignored tests are added in the end, after the "-" sign.
        Tests: "ClusterTests.*\
:BasicsTests.*\
:PreparedTests.*\
:CassandraTypes/CassandraTypesTests/*.Integration_Cassandra_*\
:BatchSingleNodeClusterTests*:BatchCounterSingleNodeClusterTests*:BatchCounterThreeNodeClusterTests*\
:ErrorTests.*\
:SslNoClusterTests*:SslNoSslOnClusterTests*\
:-PreparedTests.Integration_Cassandra_PreparedIDUnchangedDuringReprepare\
:*5.Integration_Cassandra_*\
:*19.Integration_Cassandra_*\
:CassandraTypes/CassandraTypesTests/*.Integration_Cassandra_UDT"
      run: valgrind --error-exitcode=123 ./cassandra-integration-tests --scylla --version=release:5.0.0 --category=CASSANDRA --verbose=ccm --gtest_filter="$Tests"
